baseURL = '/'
languageCode = 'en-us'
title = 'DevMhmd.com'
theme = "cactus"

[params]
  colortheme = "white" # dark, light, white, or classic
  description = "**Hey! I'm Mhmd** ğŸ‘‹.\n\nIâ€™m a Software Engineer ğŸ’», Crypto Trader ğŸª™ and Gym Enthusiast ğŸ‹ï¸â€â™‚ï¸.\n\nI was born in 1997 and grew up in a beautiful city called Alexandria ğŸŒŠ. Passionate and Self study programming since 2016 and hoping spend my life writing codes ğŸ¤©.\n\n BTW I studied Computer Science in Alexandria, University ğŸ›"

  logo = "images/gt-icon.png"
  css = [
    "css/custom.css",
    "css/scrollbar.css",
    "css/nav-tabs.css",
    # "css/darkmode.css",
  ]
  script = [
    "js/tabs.js"
  ]
  rss = true

  # ======= HomePage ======= #
  # mainSection = "projects"
  # mainSectionTitle = "Projects"

  showAllPostsOnHomePage = true
  postsOnHomePage = 5

  tagsOverview = false
  tocInline = true

  showProjectsList = true
  projectsUrl = "https://github.com/mohamed17717"

  showAllPostsArchive = true


  # ======= Social Accounts ======= #
  [[params.social]]
    name = "github"
    link = "https://github.com/mohamed17717/"

  [[params.social]]
    name = "email"
    link = "d3v.mhmd@gmail.com"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/mohamed17717/"


# ======= Navigation Bar ======= #
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4